(ns stateful-generators.generators.tuple
  (:require [clojure.test.check.generators :as gen]
            [stateful-generators.generators
             [let :as stateful-let]
             [return :as stateful-return]]))

(defn- tuple*
  [[h & rst :as sq]]
  (if (seq sq)
    (let [rst-gen (delay (tuple* rst))]
      (stateful-let/let [head h
                         tail @rst-gen]
        (into [head] tail)))
    (stateful-return/return [])))

(defn tuple
  "Create a stateful generator producing a vector where each element is
   generated by the given generator at the same position."
  [& generators]
  (tuple* generators))
