(ns stateful-generators.generators.tuple
  (:require [clojure.test.check.generators :as gen]
            [stateful-generators.generators
             [fmap :refer [fmap]]
             [bind :refer [bind]]
             [return :refer [return]]]))

(defn- tuple*
  [[h & rst :as sq]]
  (if (seq sq)
    (let [rst-gen (tuple* rst)]
      (->> (fn [head]
             (fmap #(into [head] %) rst-gen))
           (bind h)))
    (return [])))

(defn tuple
  "Create a stateful generator producing a vector where each element is
   generated by the given generator at the same position."
  [& generators]
  (tuple* generators))
